An error has occurred:
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.
Caused by: error

Trace:
func:test/Plugin/CallStack/Spec.hs:70:1-70:4
\-$fMyClassInteger:test/Plugin/CallStack/Spec.hs:90:10-90:24
\-$cmyClassFunc:test/Plugin/CallStack/Spec.hs:91:3-91:13
\-functionFromOtherModule:test/Plugin/CallStack/Spec.hs:85:1-85:23
\-wraps:test/Plugin/CallStack/OtherModule.hs:10:1-10:5
\-errorWhenTrue:test/Plugin/CallStack/OtherModule.hs:6:1-6:13