An error has occurred:
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.
Caused by: error

Trace:
func:test/Plugin/CallStack/Spec.hs:70:1-70:4
\-$fMyClassInOtherModuleInteger:test/Plugin/CallStack/OtherModule.hs:15:10-15:37
\-$fMyClassInOtherModuleInteger_$cmyClassFuncInOtherModule:test/Plugin/CallStack/OtherModule.hs:16:3-16:26